#!/usr/bin/lua

local site = require 'gluon.site_config'
local util = require 'gluon.util'

local uci = require('luci.model.uci').cursor()


local function configure_radio(radio, index, config)
  uci:delete('wireless', radio, 'disabled')

  uci:set('wireless', radio, 'channel', config.channel)
  uci:set('wireless', radio, 'htmode', config.htmode)
  uci:set('wireless', radio, 'country', site.regdom)
end


local radios = {}

uci:foreach('wireless', 'wifi-device',
      function(s)
        table.insert(radios, s['.name'])
      end
)

for index, radio in ipairs(radios) do
  local hwmode = uci:get('wireless', radio, 'hwmode')

  if hwmode == '11g' then
    configure_radio(radio, index, site.wifi24)
  elseif hwmode == '11a' then
    configure_radio(radio, index, site.wifi5)
  end
end


uci:save('wireless')
uci:save('network')
uci:commit('wireless')
uci:commit('network')
