#!/bin/sh /etc/rc.common

USE_PROCD=1
START=50

DAEMON=/usr/sbin/mmfd

start_service() {
	procd_open_instance
	procd_set_param command $DAEMON
	procd_set_param respawn ${respawn_threshold:-60} ${respawn_timeout:-1} ${respawn_retry:-0}
	procd_set_param stderr 1
	procd_set_param stdout 1
	procd_close_instance
}

service_triggers() {
	local script=$(readlink "$initscript")
	local name=$(basename "${script:-$initscript}")

	procd_open_trigger
	procd_add_raw_trigger "interface.*" 0 "/etc/init.d/$name" reload
	procd_close_trigger
}

