#!/usr/bin/lua

local site = require 'gluon.site_config'
local sysconfig = require 'gluon.sysconfig'
local uci = require 'luci.model.uci'

local c = uci.cursor()

if sysconfig.lan_ifname then
  c:section('network', 'interface', 'mesh_lan',
            { ifname = sysconfig.lan_ifname
            , proto  = 'batadv'
            , mesh   = 'bat0'
            , auto   = site.mesh_on_lan and 1 or 0
            })

  c:save('network')
  c:commit('network')
end
