#!/usr/bin/lua

local sysconfig = require 'gluon.sysconfig'
local uci = require 'luci.model.uci'

local c = uci.cursor()

if sysconfig.lan_ifname then
  if not c:get('network', 'mesh_lan') then
    c:section('network', 'interface', 'mesh_lan',
              { ifname = sysconfig.lan_ifname
              , proto  = 'batadv'
              , mesh   = 'bat0'
              , auto   = 0
              })
  end

  c:save('network')
  c:commit('network')
end
