#!/bin/sh /etc/rc.common

# olsrd starts at 65, we want to know the MACs of its neighbours from the
# first packet on
START=64
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/olsr-macd
	procd_set_param respawn
	procd_set_param stderr 1
	procd_close_instance
}
