---
name: Lint
on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lua:
    name: Lua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get install lua-check
      - name: Lint Lua
        run: luacheck .

  sh:
    name: Shell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shellcheck
        # Make sure the action is pinned to a commit, as all reviewdog repos
        # have hundreds of contributors with write access (breaks easy/often)
        uses: reviewdog/action-shellcheck@5ebd09ddbe2ebb471646ce234c6c8dd18663ca7c  # v1.30.0
        with:
          fail_level: any
          check_all_files_with_shebangs: true
          filter_mode: nofilter
